### ISSUE TITLE
ibmcloud command not provided by installer

### ISSUE THREAD

**Issue by l0s** [IBM-Bluemix-Docs/cli#79]
Issue is with this document: https://github.com/IBM-Bluemix-Docs/cli/blob/master/index.md .

After running Step 1 install command ( `curl -sL https://ibm.biz/idt-installer | bash` ), the command required for Step 2 ( `ibmcloud` ) is not available. Instead the installer indicates that the commands `idt` and `bx` are available. In order to move forward, the standalone CLI has to be installed as documented here: https://console.bluemix.net/docs/cli/reference/ibmcloud/download_cli.html#install_use .

**Comment by plindblue** [comment]
This is not expected behavior and is likely an environment specific problem and likely an issue with a bad install. I have seen users in the past uninstall and remove everything and start the install over or manually install the standalone CLI. Were you able to get past this and complete the install?

**Comment by plindblue** [comment]
Thanks for the feedback :)
